### PR TITLE
test branch wf for button

### PR DESCRIPTION
**Pull request by sahabaishakhi**

### CODE REVIEW

**Comment by azureus89** [comment]
The approach to implementing audio button function is wrong. Please try to understand the code that is inside, the solution is much much simpler, this will work, but its a bug, it will break the program in certain circumstances. Please raise an issue about documentation if you're not able to understand the code.

The approach to implementing the onclick event for the audio button is wrong, it can and should be done directly in the hello work hiccup code itself. You have done this before in the cljs boilerplate, I fail to understand why this time merited a new and more cumbersome approach?

You have uncommented line 91, this will create a state issue ... I put this line in for emergencies only. I feel like you haven't understood what is happening with audio context and how the audio is being generated, and what the buttons and start/stop are meant to do, and how they accomplish it.

If you're having issues with understanding the code please raise a documentation issue about it.

**Comment by azureus89** [comment]
Please review the above before I can merge the branch into master, currently its not mergable, the solution is not acceptable.

**Comment by sahabaishakhi** [comment]
I didn't implement it in the hello world hiccup function because I thought that we are supposed to compartmentalise html and js hence I referred to the id 'demo'. I will look into the cases where this implementation will fail. I will implement it into the hiccup code now. I have understood the code and how audio is fetched using audiocontext.. I uncommented line 91 because I wanted to stop the audio from occuring and forgot to comment it

**Comment by azureus89** [comment]
Yes in general it makes sense to separate html and js, but that approach does not exist by itself, we also need to write more stateless code etc. For now focus on the simplest solution to the problem available so you can move forward without adding too many bits and piecse to the program. For now, the more concise the solution the better. This is not always true, and it is not a value in itself. Always, horses for courses.

**Comment by azureus89** [comment]
latest implementation is still not optimal ... there is no need to include all that code inside audio button ... especially wiring, you are really loading memory by doing that ... the button is just supposed to start or stop something ... it should not be doing so much work, but im merging and editing to show you the optimal implementation

**Comment by sahabaishakhi** [comment]
I merged the latest commit you made and update my local and repos, I ran the code but the sound is produced without any need for clicking of either the screen or the button.

**Pull request merged**
